[package]
name = "rustmail_types"
version = "1.0.24"
edition = "2024"
license = "AGPL-3"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
chrono-tz = { version = "0.10.4", features = ["serde"] }
