version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 50
    reviewers:
      - "Akinator31"
    assignees:
      - "Akinator31"
    labels:
      - "dependencies"
      - "ðŸ¦€ rust"
    commit-message:
      prefix: "cargo"
      include: "scope"