[package]
name = "rustmail_types"
version = "1.0.8"
edition = "2024"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono-tz = { version = "0.10", features = ["serde"] }
